spring:
  profiles:
    active: @spring.profiles.active@
  data:
    mongodb:
      database: 
      host: 
      username: 
      password: 
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:site/**/mapper/*.xml
